### ISSUE TITLE
can't run script "Exception in thread"

### ISSUE THREAD

**Issue by Kellsen** [zmalrobot/JavaLinuxUndervolt#3]
I get the error message(s) when I try to run the "run.sh" script or "sudo java -jar DownvoltLinuxUi.jar"

Eseguo: sudo resource/externaltools/undervolt.py --read
Script say : core: 0.0 mV
Adding: core 0.0
Script say : gpu: 0.0 mV
Adding: gpu 0.0
Script say : cache: 0.0 mV
Adding: cache 0.0
Script say : uncore: 0.0 mV
Adding: uncore 0.0
Script say : analogio: 0.0 mV
Adding: analogio 0.0
Script say : powerlimit: 25.0W (short: 0.00244140625s - enabled) / 15.0W (long: 28.0s - enabled)
Adding: powerlimit 25.0W(short
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "25.0W(short"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at UndervoltValue.addToHasmap(UndervoltValue.java:111)
	at UndervoltValue.runScript(UndervoltValue.java:84)
	at UndervoltValue.getValue(UndervoltValue.java:27)
	at Interface.setUiValue(Interface.java:259)
	at Interface.<init>(Interface.java:152)
	at Main$1.run(Main.java:20)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ulrickpsp** [comment]
Same issue here
